In [2]:
import numpy as np

**Basic Array Creation**

In [3]:
arr = np.array([1, 2, 3])
arr

array([1, 2, 3])

In [5]:
arr = [1, 2, 3, "hello"]
arr

[1, 2, 3, 'hello']

In [6]:
np.array(arr)

array(['1', '2', '3', 'hello'], dtype='<U21')

In [7]:
l = [[1, 2, 3], [4, 5, 6]]
l

[[1, 2, 3], [4, 5, 6]]

In [8]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6]])

**Array Generation functions**

In [9]:
arr = np.arange(1, 11, 2)
arr

array([1, 3, 5, 7, 9])

In [10]:
arr = np.zeros((4, 8))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [14]:
arr = np.linspace(1, 5, 10)
arr

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

**Random Generation functions**

In [15]:
np.random.rand(10)

array([0.34459803, 0.69460304, 0.40179334, 0.88161214, 0.1687803 ,
       0.34944088, 0.2080707 , 0.52216522, 0.18518662, 0.61405717])

In [16]:
np.random.randn(10)

array([-0.51293745, -1.43325694,  0.26242064,  0.44109723, -0.20292537,
       -0.08474389, -0.45110942,  0.9819793 , -0.41459226, -0.50027816])

In [18]:
np.random.randint(10, 20, 5)

array([16, 11, 13, 18, 18], dtype=int32)

**Array Attributes**

In [21]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
arr.shape

(3, 3)

In [26]:
arr.size

9

In [28]:
arr.dtype

dtype('int64')

**Array Methods**

In [30]:
arr.min()

np.int64(1)

In [31]:
arr.max()

np.int64(9)

In [32]:
arr.sum()

np.int64(45)

In [36]:
np.sum(arr, axis=1)

array([12, 15, 18])

In [38]:
arr.mean()

np.float64(5.0)

In [40]:
arr.argmax()

np.int64(8)

**Reshaping and Resizing**

In [42]:
arr = np.arange(1, 31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [45]:
arr = arr.reshape(5, 6)
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])